### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by F21** [arteniioleg/color-scheme#1]
I received this error after installing the theme and opening PHPStorm:

```
Cannot read scheme moldcraft.icls  from '$ROOT_CONFIG$/colors': Error on line 31: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
```

I am using PHPStorm 7.1.3 on Windows 8.1.

**Comment by prograhammer** [comment]
I had the same problem, finally I went to the "raw" file on github, then right click > save as, and it finally worked.
